# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a65bb766b73f9c802dea02cd6fa9d680a81341c75bb1182a66cb8f1f0479e146bdff7dd0d687af6938772b1e7b43498f202055cf264375152571baad6c5dad7

test:
  secret_key_base: f665f4503e1bc118422846981b8669ba5feac2ace996e3a446fd1d8483f6b2932b636e81b89324c5485eaf06f053ad7f18491de99c23194e5fe3aaf1a1fabea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c516b416c754b18c7ea55ffa72859e1c8988218b91e15b5c473d7fed09cbd5a3bd846819fcad2a079a8fd759a113987c0efdf59d5c490ab925ceb67b3329a6de
